### ISSUE TITLE
Disassembler

### ISSUE THREAD

**Issue by trufae** [rigel314/pebbleSystemInfo#1]
If you need a disassembler you may take the one from winedbg guys, which is pretty small and can be easily stripped to remove the non-thumb part.

Here's my fork:

https://github.com/radare/radare2/tree/master/libr/asm/arch/arm/winedbg

otherwise, i'll try to hack on that when i receive my pebble :) thanks for such piece of soft

**Comment by rigel314** [comment]
That looks great.  I'm glad someone is as ridiculous as me.  I will incorporate this when I get some time.  If you feel like working on it, you can always make a pull request.

**Comment by trufae** [comment]
Im totoally out of time right now. I just got the pebble yesterday and i didnt compiled anything for it yet. But i plan to do some apps as soon as i get some spare time :)

**Comment by radare** [comment]
Any update?

**Comment by radare** [comment]
I just did my own disassembler tool for the Pebble: https://github.com/radare/pebble-disthumb

i would like to integrate this code into your tool, but it needs to be updated to work with the latest SDK because of the deprecated InvertedLayer thing. Would you want to continue maintaining your project?

**Comment by rigel314** [comment]
I do want to continue maintaining my project. I just don't have a pebble
time yet so it's not a high priority.  I really should update the code to
work with the latest SDK.  I'll do that in the next couple days.

**Comment by radare** [comment]
awesome! i'll stay tuned

**Comment by rigel314** [comment]
Closed by [a912a1](https://github.com/rigel314/pebbleSystemInfo/commit/a912a10ace533ca9f251c783eebc89b5c1a10e3b)
